version: '3.8'
services:
  speechify:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./:/home/node/app/
      - node_modules:/home/node/app/node_modules/
    environment:
      - NODE_ENV=development
volumes:
  node_modules: {}